apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-all-zarf-to-minio-9000-debug
  namespace: minio
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        ports: ["9000"]